### ISSUE TITLE
Create requirements.txt file

### ISSUE THREAD

**Issue by alexander-esser** [LenzGr/pytalent-monitor#10]
Thank you very much for publishing this Python project!
I currently have some issues with the Talent Home app on my smartphone. Thus, I connected to my TSUN-TSOL microinverter using this package.

A `requirements.txt` would be great, so that users can easily install all required packages by

```
pip install -r requirements.txt
```

Currently, the `requirements.txt` file would only contain one line

```
aiohttp
```

When releasing the first version of this package, each dependency should be freezed to a fixed version, to make the code reproducible, e.g.

```
aiohttp==3.9.5
```

And one more idea: Not every user might use `hatch`. In the `README.md` file, you could add the alternative command

```
python pyTalentMonitor\__init__.py -u <User> -p <Password> 
```

for general users.

**Comment by LenzGr** [comment]
Thanks for the feedback, @alexander-esser - good ideas, I'll make the necessary changes.
