### ISSUE TITLE
Bug: PV module request broken

### ISSUE THREAD

**Issue by encarsia** [LenzGr/pytalent-monitor#5]
Hi,

this  used to work but I figured that the pv module data isn't in the response json from the "selectLayoutComponents" request anymore and therefore throws an error.
Maybe this is due a firmware update, I have a TSOL-MS600 with firmware version 5.0.11.

Could you test if this still works for you? If not, good news everyone, I can provide the fix that works for me.

Regards

**Comment by LenzGr** [comment]
Thanks for the report. This is likely not related to firmware updates on your inverter, but rather to changes in the REST API itself. The script fails for me too. If you have already found a solution, I'd greatly appreciate a pull request!

**Comment by encarsia** [comment]
Done.

**Comment by LenzGr** [comment]
Thank you for your contribution! I appreciate your help.
