### ISSUE TITLE
"Authentication failed" error when using valid login credentials

### ISSUE THREAD

**Issue by LenzGr** [LenzGr/pytalent-monitor#8]
It seems the remote API endpoint has changed behaviour. Running `hatch run pyTalentMonitor/__init__.py` after setting a known username and password via environment variables or by passing them as arguments fails with the following error:
```
$ hatch run pyTalentMonitor/__init__.py
ERROR:root:Login failed. Got status code 200
Traceback (most recent call last):
  File "/Users/lenz/work/pytalent-monitor/pyTalentMonitor/__init__.py", line 137, in <module>
    result = talent_monitor.fetch_solar_data()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lenz/work/pytalent-monitor/pyTalentMonitor/__init__.py", line 67, in fetch_solar_data
    self.login()
  File "/Users/lenz/work/pytalent-monitor/pyTalentMonitor/__init__.py", line 42, in login
    raise AuthenticationError("Authentication failed")
AuthenticationError: Authentication failed
```

**Comment by LenzGr** [comment]
Changing the log level to DEBUG and adding some more debug output reveals the following:
```
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.talent-monitoring.com:443
DEBUG:urllib3.connectionpool:https://www.talent-monitoring.com:443 "POST /prod-api/login HTTP/1.1" 200 None
DEBUG:root:Response Data: {'msg': 'Captcha is no longer valid', 'code': 500}
ERROR:root:Login failed. Got status code 200
Traceback (most recent call last):
  File "/Users/lenz/work/pytalent-monitor/pyTalentMonitor/__init__.py", line 138, in <module>
    result = talent_monitor.fetch_solar_data()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lenz/work/pytalent-monitor/pyTalentMonitor/__init__.py", line 68, in fetch_solar_data
    self.login()
  File "/Users/lenz/work/pytalent-monitor/pyTalentMonitor/__init__.py", line 43, in login
    raise AuthenticationError("Authentication failed")
AuthenticationError: Authentication failed
```
This `Captcha is no longer valid` error seems to be the root cause of this failure. But how to fix it remains to be seen.

**Comment by StephanU** [comment]
When loading the talent monitor website (without logging in), the website sends a request to an endpoint `/prodapi/captchaimage` which returns a base64 encoded image of a captcha. 
<img width="1784" alt="Bildschirmfoto 2024-05-21 um 21 57 58" src="https://github.com/LenzGr/pytalent-monitor/assets/514422/184fa8dd-cfc3-4b50-b332-d9fec42c14ae">

But this is captcha is not shown on the page, also not when logging in... really strange.
Could you try logging in via the website and afterwards run your script?

**Comment by LenzGr** [comment]
I can not reproduce this error anymore, might have been an issue on my end.
